#!/bin/bash

# $Id$

# This script is used to compile the python module used for geometry reconstruction.
# It uses the fortran wrapper f2py that is included in the numpy package to construct the
# module postprocessingMath.so out of the fortran code postprocessingMath.f90

# for the generation of the pyf file:
# f2py -m postprocessingMath -h postprocessingMath.pyf --overwrite-signature postprocessingMath.f90

# use ./configure --enable-sse2 --enable-shared for the compilation of fftw3.3

if [[ $# -eq 0 ]]; then
  wd='.'
else
  wd=$1
fi

cd $wd
rm ../../lib/postprocessingMath.so
f2py -c \
postprocessingMath.pyf \
postprocessingMath.f90 \
../../lib/libfftw3.a \
-L./
mv postprocessingMath.so ../../lib/.
