        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 23 16:12:31 2016
        MODULE QUIT__genmod
          INTERFACE 
            SUBROUTINE QUIT(STOP_ID)
              INTEGER(KIND=4), INTENT(IN) :: STOP_ID
            END SUBROUTINE QUIT
          END INTERFACE 
        END MODULE QUIT__genmod
