#!/bin/bash

if [[ $# < 2 ]]; then  # check the number of command line arguments
	echo "usage: $0 homogenization_scheme constitutive_law"
	exit
fi

if [[ !(-f "CPFEM_$1.f90") ]]; then
	echo "no file CPFEM_$1.f90 present"
else
	if [[ !(-f "constitutive_$2.f90") ]]; then
		echo "no file constitutive_$2.f90 present"
		exit
	else
		rm CPFEM.f90
		ln -s CPFEM_$1.f90 CPFEM.f90
		rm constitutive.f90
		ln -s constitutive_$2.f90 constitutive.f90
	fi
fi
