type: quadenergy
V_m: 1.0e-5
output: [x]

species:
  H:
    M: 1
    c_0: 1
    c_eq: 1
    G,c: 1
    G,c^2: 1
  Cl:
    M: 1
    c_0: 1
    c_eq: 1
    G,c: 1
    G,c^2: 1
  Cu:
    M: 1
    c_0: 1
