name: build-push
run-name: 'build-push: repo? ${{ github.event.inputs.repo }} - latest? ${{ github.event.inputs.latest }} - custom_tag? ${{ github.event.inputs.custom_tag }}'

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'ghcr.io repository where image will be pushed'
        required: true
        type: string
        default: ""
      latest:
        description: 'Push with "latest" tag?'
        required: true
        type: boolean
        default: true
      custom_tag:
        description: 'Specify a custom tag to push'
        required: false
        type: string
        default: ""

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: damask:testing
        
      - name: Test
        run: |
          expected="STOP 0"
          actual=$(docker run damask:test --help 2>&1 >/dev/null)
          if [ "$expected" = "$actual" ]; then
            echo "Passed -   $actual"
          else
            echo "ERROR - Expected: $expected"
            echo "          Actual: $actual"
            status=1
          fi

          exit $status
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push versioned
        if: github.event.inputs.custom_tag != ''
        run: |
          docker image tag damask:testing ghcr.io/${{ github.event.inputs.repo }}/damask:${{ github.event.inputs.custom_tag }}
          docker push ghcr.io/${{ github.event.inputs.repo }}/damask:${{ github.event.inputs.custom_tag }}

      - name: Push latest
        if: github.event.inputs.latest == 'true'
        run: |
          docker image tag damask:testing ghcr.io/${{ github.event.inputs.repo }}/damask:latest
          docker push ghcr.io/${{ github.event.inputs.repo }}/damask:latest
